### PR TITLE
Added options to verify() function

### PR DESCRIPTION
**Pull request by LaurentMT**
PR related to issue #9 

Added options parameters to verify() function:

options.insight.urls - {string[]} - array of insight server urls
    more than 2 urls are required, otherwise fallback to default list

options.insight.timeout - {integer} - timeout for requests sent to insight servers
    timeout expressed in seconds

### CODE REVIEW

**Comment by lvaccaro** [comment]
The code is OK, we use a lint tool in the build process. Can you resolve xo warnings in order to fix the build? 
Install xo tool with:
` $ npm install --only=dev`
Run xo tool to check the warnings:
` $ xo`

**Comment by LaurentMT** [comment]
Oops.. Sorry about that. I should have checked the results here.

Fixes pushed in last commit. Seems ok now.

For the record: I've also changed the timeout value used in a unit test (from 5s to 20s) to be sure that it doesn't break the unit tests.

**Comment by RCasatta** [comment]
Look great, thanks!

**Comment by RCasatta** [comment]
@LaurentMT  For your reference, in case of a bitcoin node available on the test machine, the test https://github.com/opentimestamps/javascript-opentimestamps/blob/0358c7822394b1bf1f4ae162bdbda8ac1e22ea6a/test/open-timestamps.js#L306 fails because there is no exception in that case. I decided to force lite client verification if insight urls are passed through options with https://github.com/opentimestamps/javascript-opentimestamps/commit/f9172e8f481a9ec40e1c216a76df127f7e1f9d1f

**Pull request merged**
