### PR TITLE
Remove Ethereum attestation

### PR DESCRIPTION
**Pull request by RCasatta**
remove support for the keccak hash op used for Ethereum proof
since there is no calendar running on etheurem

### CODE REVIEW

**Comment by lvaccaro** [comment]
Concept ack 1275462acdf164ee347278351034376abb3ae63b . Remove .swp file added in 1275462acdf164ee347278351034376abb3ae63b .
Should previously eth attestations displayed as unknown attestation with following tag `30fe8087b5c7ead7` ?

**Comment by petertodd** [comment]
How about I ask on Twitter if anyone is using this first?

**Comment by RCasatta** [comment]
my idea was to leave this open for a while and see if someone complains, asking on twitter will speed up thing in one direction or the other so perfect

**Comment by ilmesi** [comment]
Is there any technical reason to drop support on eth attestations? If the only one is the lack of popularity, I believe Litecoin attestations will run the same luck, what will make this protocol more about a tool around Bitcoin than any other thing..

**Comment by Kexkey** [comment]
ACK.  Just FYI, we at BullBitcoin are not stamping on Ethereum and as far as we know, it never went live at Catallaxy, two years ago, when there was work on it.  We are not aware of people using it.

**Comment by RCasatta** [comment]
@ilmesi the biggest technical reason is that mantaining an ethereum full node, necessary for the calendar, is not that easy. Moreover as you can see from this PR there is a lot of code that could be removed. The spark started when I had problem in the keccak dependancy library, specifically required for ethereum (others required hash functions are together).
Not sure what will do with litecoin, at least litecoin doesn't need his specific hash function.

**Comment by ilmesi** [comment]
@RCasatta I understand the problems with mantaining the ethereum full node, I think that is the issue here. I don't think the realiability and/or popularity of eth attestations is something to discuss when building a standard.

**Comment by petertodd** [comment]
> @RCasatta I understand the problems with mantaining the ethereum full node, I think that is the issue here. I don't think the realiability and/or popularity of eth attestations is something to discuss when building a standard.

I mean, we already have: the offical OTS protocol standard is currently the [Python implementation](https://github.com/opentimestamps/python-opentimestamps), which puts the ETH attestation under the [dubious](https://github.com/opentimestamps/python-opentimestamps/blob/3cdda8296bdb2e177f4a6b8bc0d37c10c5506df1/opentimestamps/core/dubious/notary.py#L23) module for exactly these reasons.

Anything in the standard is a potential liability from a security/maintenance point-of-view, so we need to have good reasons to keep any part of the standard that isn't getting used. I think especially that we need a specific, slightly non-standard, hash function for this is a good argument against keeping this functionality.

**Comment by petertodd** [comment]
> Not sure what we will do with litecoin, at least litecoin doesn't need his specific hash function.

Yeah, Litecoin so far doesn't require much effort to keep. Though I'd be against adding Litecoin proof verification to the clients - for the **very** rare time when Litecoin is used seems like verifying by hand should be fine.

**Comment by petertodd** [comment]
@rcasatta Note that in the future, when we're discussing a protocol change like this it'd be better to submit the pull-req first to python-opentimestamps (and at some point rust-opentimestamps) to keep this kind of discussion with the protocol specification.

**Comment by jb55** [comment]
ACK  1275462acdf164ee347278351034376abb3ae63b

**Comment by lvaccaro** [comment]
Moreover `web3` npm package has a security vulnerability related to the Insecure Credential Storage https://www.npmjs.com/advisories/877

**Pull request merged**
